server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nilankajayasaman/n-java-training
          search-paths:
            - 'assignment-2/Conf'
