server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nilankajayasaman/n-java-training/tree/master/assignment+2/Conf
          search-paths:
            - 'service-config/*service'
