server:
  port: 8282
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  config:
    name:
      application: employee-service
  datasource:
    url: jdbc:mysql://ems-mysql:3306/ems?createDatabaseIfNotExist=true
    username: root
#    password: 123
    password: 1qaz2wsx@
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      minimumIdle: 10
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
security:
  oauth2:
    resource:
      token-info-uri: http://auth:9090/oauth/check_token
    client:
      client-id: web
      client-secret: pin



