security:
  oauth2:
    client:
      client-id: web
      client-secret: pin
      user-authorization-uri: http://auth-srv:8383/oauth/authorize
      access-token-uri: http://auth-srv:8383/oauth/token
    resource:
      token-info-uri: http://auth-srv:8383/oauth/check_token
server:
  port: 8080
  servlet:
    session:
      cookie:
        name: KSESSIONID

