server:
  port: 8383
spring:
  config:
    name:
      application: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/oAuth_EMS_DB?createDatabaseIfNotExist=true
    username: root
    password: 1qaz2wsx@
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      minimumIdle: 10
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create
    show-sql: true
    format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:8282/oauth/check_token
#    client:
#      client-id: web
#      client-secret: webpass

